export const GET_SINGLEPRODUCTS_REQUEST = "GET_SINGLEPRODUCTS_REQUEST";
export const GET_SINGLEPRODUCTS_SUCCESS = "GET_SINGLEPRODUCTS_SUCCESS";
export const GET_SINGLEPRODUCTS_FAILURE = "GET_SINGLEPRODUCTS_FAILURE";